# Generated by Django 5.1.4 on 2025-01-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_views_alter_productimage_image_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_orders',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
