# Generated by Django 5.1.4 on 2025-01-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_total_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(null=True, related_name='products', to='products.size'),
        ),
    ]
